package com.gyanu.trider.presentation

sealed class AppEvents {
    object ClearPickupAddressText:AppEvents()
    object PickUpAddressTextChanged:AppEvents()
    object ClearDropAddressText:AppEvents()
    object ClearSelectedDropAddressText:AppEvents()
    object ClearSelectedDropAddressText2:AppEvents()
    object ClearDropAddressText2:AppEvents()
    object DropAddressTextChanged:AppEvents()
    object SelectedDropAddressTextChanged:AppEvents()
    object SelectedDropAddressTextChanged2:AppEvents()
    object DropAddressTextChanged2:AppEvents()
    object OpenMenuNavigationDrawer:AppEvents()
    object PickupCamMoving:AppEvents()
    object DropCamMoving:AppEvents()
    object DropCamMoving2:AppEvents()
    object FetchPickupLocation:AppEvents()
    object FetchPickupLocaionCoords:AppEvents()
    object FetchDropLocation:AppEvents()
    object  FetchSelectedDropLocation:AppEvents()
    object  FetchSelectedDropLocation2:AppEvents()
    object FetchDropLocaionCoords:AppEvents()
    object FetchSelectedDropLocaionCoords:AppEvents()
    object FetchSelectedDropLocaionCoords2:AppEvents()
    object FetchDropLocation2:AppEvents()
    object FetchDropLocaionCoords2:AppEvents()
    object GetDirections:AppEvents()
    object GetDirections2:AppEvents()
    object ResetDestinations:AppEvents()
    object ResetDestinations2:AppEvents()
    object ResetSelectedDestinations:AppEvents()
    object ResetSelectedDestinations2:AppEvents()
    object AllowNavigation:AppEvents()
    object StopNavigation:AppEvents()
    object BlurMap:AppEvents()
    object UnBlurMap:AppEvents()
    object AddSecondDestination:AppEvents()
    object RemoveSecondDestination:AppEvents()
    object  ConfirmDrop:AppEvents()
    object  ConfirmDrop2:AppEvents()
    object  ToggleMapType:AppEvents()
    object  EnableMyLocation:AppEvents()

}